user:
  min_password_length: 0
  max_password_length: 20
  user_per_page: 10
  user_follower_per_page: 1
  user_followed_per_page: 10
  user_high_score: 10
omniauth:
  facebook: "facebook"
  google_oauth2: "google_oauth2"
course:
  course_per_page: 20
